---
title: "Day3"
author: "Kristoffer Sundström"
date: "`r Sys.Date()`"
output: html_document
---

Install and load important packages:
```{r}
library(tidyverse)
```


** PART 1 **

Import the dataset:
```{r}
data <- read_lines("~/GitHub/Advent-of-Code/2024/Inputs/Day3.txt")
```

Find the certain numbers that are enclosed by mul() and separated by a ,:
```{r}
data <- data %>%
  str_match_all("mul\\((\\d+),(\\d+)\\)") %>% # Match together all the strings that matches the specified condition.
  map(~ .[, 2:3]) %>% # Extract the numbers.
  unlist() %>% # Unlist the list.
  data.frame() # Put it all in a dataframe.

data <- data %>%
   mutate(index = row_number(),
         group = if_else(index %% 2 == 1, "Vector 1", "Vector 2")) %>% # Create an index and name them vector 1 and vector 2 based on even and uneven row numbers.
  ungroup() %>% # Once again ungroup.
  rename(Values = !!names(data)[1]) # Rename the first column to "Values".

# Separate into two vectors: odd-indexed and even-indexed rows
vector_1 <- data %>%
  filter(row_number() %% 2 != 0) %>%
  .$. %>%
  as.numeric()

vector_2 <- data %>%
  filter(row_number() %% 2 == 0) %>%
  .$. %>%
  as.numeric()

sum(vector_1 * vector_2)
```

